# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: GitHub Actions Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GH_TOKEN: ${{ github.token }}
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
      
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checking if Run unit tests have finished
        run: |
          while [[ "$(gh run list --workflow 'Run unit tests' --branch master --json conclusion --jq '.[0].conclusion')" != "success" ]]; do
            echo "$(gh run list --workflow 'Run unit tests' --branch master --json conclusion --jq '.[0].conclusion')"
            echo "Waiting for Run unit tests to finish..."
            sleep 30
          done
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}